# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'
use_frameworks!

inhibit_all_warnings!

def shared_pods

	pod 'Charts'
  pod 'HSStockChart'
  pod 'SwiftyJSON'
  pod 'GDPerformanceView-Swift'
  
end

target 'Front' do

  shared_pods

end
